quarkus:
  hibernate-orm:
    database:
      generation: none
  datasource:
    jdbc:
      url: ${DATABASE_URL:urlDoBanco_schema}
    db-kind: postgresql
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD:password}
  http:
    port: 8090
kafka:
  bootstrap:
    servers: localhost:9092
mp:
  messaging:
    outgoing:
      challenge:
        connector: smallrye-kafka
        topic: intention-transfer
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer
        key:
          serializer: org.apache.kafka.common.serialization.StringSerializer